import {
  OPENAI_TTS_FORMAT_ORDER,
  type OpenAITTSAudioData,
  type OpenAITTSPayload,
  type OpenAITTSResponseFormat,
} from '@/libs/openaiTTS';

export { OPENAI_TTS_FORMAT_ORDER } from '@/libs/openaiTTS';

const CODEC_PROBE_TIMEOUT_MS = 2000;

// Valid, deterministic, mono probe files generated from a 440 Hz tone. Opus
// uses FFmpeg 8.1; AAC uses Apple's afconvert because WebKit rejected
// the smaller FFmpeg-authored M4A during real-browser validation. They are
// deliberately embedded so probing works offline and in every Readest shell
// through the exact AudioContext.decodeAudioData path used for real speech.
// The files are Ogg Opus (312 B) and AAC-LC/M4A (4692 B).
// biome-ignore format: Keep generated fixture payloads visually separate.
const PROBE_BASE64: Record<OpenAITTSResponseFormat, string> = {
  opus:
    'T2dnUwACAAAAAAAAAAAAAAAAAAAAAAIotXIBE09wdXNIZWFkAQE4AYC7AAAAAABPZ2dTAAAAAAAAAAAAAAAAAAABAAAASZW+VAEuT3B1c1RhZ3MGAAAAZmZtcGVnAQAAABQAAABlbmNvZGVyPUxhdmMgbGlib3B1c09nZ1MABHgMAAAAAAAAAAAAAAIAAADlTPZNBCgoKCh4ggKwNe0RraUhPAk8ScdzDdV+USSb0t9P0FYexKOtp6LuqROpTQA9eKp+n1fjKbyZD4QWYjk1+DID+v5lOUCjzwItwkrrWFjxelTLCmtJRXicSug7zjEstPCvS7LI0v0yxDDSqxqMG2f+rsbf11z9OaqWqjTZ8fF4Bk2mg80Z7cOqMdEFnXjqXa0EAq641V42lAHBCrIo7zwenaOI9ffH',
  aac:
    'AAAAHGZ0eXBNNEEgAAAAAE00QSBtcDQyaXNvbQAAA05tb292AAAAbG12aGQAAAAA5nXDgOZ1w4AAALuAAAAcAAABAAABAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAB4HRyYWsAAABcdGtoZAAAAAfmdcOA5nXDgAAAAAEAAAAAAAAcAAAAAAAAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAXxtZGlhAAAAIG1kaGQAAAAA5nXDgOZ1w4AAALuAAAAcAAAAAAAAAAAiaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAAAAAAABMm1pbmYAAAAQc21oZAAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAA9nN0YmwAAAB2c3RzZAAAAAAAAAABAAAAZm1wNGEAAAAAAAAAAQAAAAAAAAAAAAIAEAAAAAC7gAAAAAAAM2VzZHMAAAAAA4CAgCIAAAAEgICAFEAUABgAAAAAAAAA+gAFgICAAhGIBoCAgAECAAAAD3NidGQAAAAASTE2AAAAGHN0dHMAAAAAAAAAAQAAAAcAAAQAAAAAHHN0c2MAAAAAAAAAAQAAAAEAAAAHAAAAAQAAADBzdHN6AAAAAAAAAAAAAAAHAAAABAAAAIAAAABrAAAARQAAAEoAAAB2AAAAYAAAABRzdGNvAAAAAAAAAAEAABAAAAAA+nVkdGEAAADybWV0YQAAAAAAAAAiaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAAxGlsc3QAAAC8LS0tLQAAABxtZWFuAAAAAGNvbS5hcHBsZS5pVHVuZXMAAAAUbmFtZQAAAABpVHVuU01QQgAAAIRkYXRhAAAAAQAAAAAgMDAwMDAwMDAgMDAwMDA4NDAgMDAwMDAxMDAgMDAwMDAwMDAwMDAwMTJDMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMCAwMDAwMDAwMAAADI5mcmVlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJcbWRhdADQQAcBMJnYPbMY4Bsp0CT4+PPWsvH/9l8dffjjgQ60CgIf1YF4f6kCgXWgURD1NeuRCWVfWti4rV46C8Wc8dS/Z3RL6QcWcY6l63GtZxjmOJYl4ttNnBOYQliD/03/TZrzf9N/039UKWbOzsgbOzsgZalcOyBISEhISEhISEhImGphhwEa1KywdGCwCqf0zOnS/xd/Cy4MClQLlTIBBpAHhIyWoNHNOsLT3aSKvdY26xpzU5o7ghCHazWVRRBTk/ivxVkV+mTRMssqRJogaRlkk8WNGkzRsHPcFxnCDSAFbkAVACgAQiBUjATUAGZwAQwUrMBSSIwEIQGIQIIQM9Z+fW//d970tgyi5VYQ4I4JZbS5XVHGItuyzYioXFEBFFFFFFFFyiyxEQGIUoIJKAukCag4ARQUrMBEEAkMIwEIQGJQOe/v81/18/r0HZMQXKSBA41NLqhp5ZGWWKs2KxU0wSEzBOidM7aVSnEuAk5MhqABHpzkCYAAEgABObgBHFSs8FIjCQguApn8VnDh8eenT2UAb03FC5V0iQkIAAe4s2JhEUhdPsbXUYCCHRSCRSCTGJjAHJt1c/u8eefZPNNNxqq5TPTVfVfUZuv3YcyioEMzdfOKkMy9dKFFyUPQOsGQAMd1Ik4yxVAAEibAACAKADA4AT6ZPqMlQoFRalAQevr8fV3qVP/4n10/Dpb1frD9er+Eh/mzCI+BAchzSTWH05sgPHyawv5flax6uSoIaOU1swezy7OYdnPPMfD4dB0+HTDZVoCYJjYKSYnmc7zGMYxn',
};

export const getOpenAITTSProbeData = (format: OpenAITTSResponseFormat): ArrayBuffer => {
  const binary = globalThis.atob(PROBE_BASE64[format]);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
  return bytes.buffer;
};

export class OpenAITTSCodecExhaustedError extends Error {
  constructor() {
    super('This runtime or speech server could not provide a decodable Opus or AAC stream.');
    this.name = 'OpenAITTSCodecExhaustedError';
  }
}

type ProbeDecoder = (data: ArrayBuffer) => Promise<unknown>;

// One negotiator is owned by one OpenAITTSClient endpoint session. Rejections
// only move forward, so concurrent lookahead jobs can never re-enable a codec
// that another job has already proved unusable.
export class OpenAITTSCodecNegotiator {
  readonly #decode: ProbeDecoder;
  readonly #probeResults = new Map<OpenAITTSResponseFormat, Promise<boolean>>();
  #minimumIndex = 0;
  #pinnedFormat: OpenAITTSResponseFormat | null = null;

  constructor(decode: ProbeDecoder) {
    this.#decode = decode;
  }

  get pinnedFormat(): OpenAITTSResponseFormat | null {
    return this.#pinnedFormat;
  }

  get minimumFormat(): OpenAITTSResponseFormat | null {
    return OPENAI_TTS_FORMAT_ORDER[this.#minimumIndex] ?? null;
  }

  accepts(format: OpenAITTSResponseFormat): boolean {
    const index = OPENAI_TTS_FORMAT_ORDER.indexOf(format);
    if (index < this.#minimumIndex) return false;
    return this.#pinnedFormat === null || this.#pinnedFormat === format;
  }

  reject(format: OpenAITTSResponseFormat): void {
    const index = OPENAI_TTS_FORMAT_ORDER.indexOf(format);
    if (index < 0) return;
    this.#minimumIndex = Math.max(this.#minimumIndex, index + 1);
    if (this.#pinnedFormat === format) this.#pinnedFormat = null;
  }

  pin(format: OpenAITTSResponseFormat): void {
    const index = OPENAI_TTS_FORMAT_ORDER.indexOf(format);
    if (index < this.#minimumIndex) return;
    this.#minimumIndex = index;
    this.#pinnedFormat = format;
  }

  async nextFormat(): Promise<OpenAITTSResponseFormat> {
    if (this.#pinnedFormat) return this.#pinnedFormat;
    for (let index = this.#minimumIndex; index < OPENAI_TTS_FORMAT_ORDER.length; index++) {
      const format = OPENAI_TTS_FORMAT_ORDER[index]!;
      if (index < this.#minimumIndex) continue;
      const supported = await this.#probe(format);
      // Another concurrent request may have rejected this format while its
      // shared runtime probe was pending.
      if (index < this.#minimumIndex) continue;
      if (supported) return format;
      this.reject(format);
    }
    throw new OpenAITTSCodecExhaustedError();
  }

  #probe(format: OpenAITTSResponseFormat): Promise<boolean> {
    const existing = this.#probeResults.get(format);
    if (existing) return existing;
    const probe = new Promise<boolean>((resolve) => {
      let done = false;
      const finish = (supported: boolean) => {
        if (done) return;
        done = true;
        clearTimeout(timer);
        resolve(supported);
      };
      const timer = setTimeout(() => finish(false), CODEC_PROBE_TIMEOUT_MS);
      this.#decode(getOpenAITTSProbeData(format)).then(
        () => finish(true),
        () => finish(false),
      );
    });
    this.#probeResults.set(format, probe);
    return probe;
  }
}

export interface OpenAITTSFetchedAudio<TPayload extends OpenAITTSPayload = OpenAITTSPayload> {
  format: OpenAITTSResponseFormat;
  payload: TPayload;
  audio: OpenAITTSAudioData;
}

// Decode the real sentence through the same decoder used by the probes. A
// real-stream decode failure evicts those bytes, advances the ladder, and
// refetches this same sentence. Other errors are deliberately left to fetch
// and playback code so auth/rate-limit/network failures cannot pin a downgrade.
export const decodeOpenAITTSAudioWithFallback = async <
  TFetched extends OpenAITTSFetchedAudio,
  TDecoded,
>(
  initial: TFetched,
  options: {
    negotiator: OpenAITTSCodecNegotiator;
    decode: (data: ArrayBuffer) => Promise<TDecoded>;
    refetch: () => Promise<TFetched>;
    evict: (payload: TFetched['payload']) => void;
  },
): Promise<{ fetched: TFetched; decoded: TDecoded }> => {
  let fetched = initial;
  for (let attempt = 0; attempt <= OPENAI_TTS_FORMAT_ORDER.length; attempt++) {
    if (!options.negotiator.accepts(fetched.format)) {
      options.evict(fetched.payload);
      fetched = await options.refetch();
      continue;
    }
    try {
      const decoded = await options.decode(fetched.audio.data);
      options.negotiator.pin(fetched.format);
      return { fetched, decoded };
    } catch {
      options.evict(fetched.payload);
      options.negotiator.reject(fetched.format);
      fetched = await options.refetch();
    }
  }
  throw new OpenAITTSCodecExhaustedError();
};
